name: "Main / Pull requests build"
on:
    workflow_dispatch:
 
jobs:
    build:
        runs-on: self-hosted
        strategy:
            fail-fast: true
            max-parallel: 1
        steps:
            -   uses: actions/checkout@v4.1.6
            -   name: Set up JDK 23
                uses: actions/setup-java@v4.2.1
                with:
                    distribution: 'temurin'
                    java-version: 23
                    architecture: x64
                    cache: 'maven'
            -   name: Build with Maven
                run: ./mvnw --no-transfer-progress verify
