name: "Build"

on:
  workflow_dispatch:

jobs:
  pre-commit:
    name: Pre-commit check
    runs-on: self-hosted
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4.1.6

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4.1.6

      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '21'
          architecture: x64
          cache: 'maven'

      - name: Build with Maven
        run: .\mvnw.cmd clean package -DskipTests --no-transfer-progress
